spring:
  application:
    name: Ekalavya

  # DataSource Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/ekalavya_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    initialization-mode: always

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

  # DevTools Configuration
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  # Mail Configuration
  mail:
    host: smtp.gmail.com
    username: chittaranjanpal049@gmail.com
    password: biwriurddpmcnwgh
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  main:
    allow-bean-definition-overriding: true

  freemarker:
    template-loader-path: classpath:/templates/email-template/
    suffix: .ftl

# Server Configuration
server:
  port: 61002

# Logging Configuration
logging:
  level:
    com.ekalavya.org: INFO
base:
  url: http://localhost:61002