INSERT INTO role (name) VALUES ('PM');
INSERT INTO role (name) VALUES ('DOMAIN EXPERT');
INSERT INTO role (name) VALUES ('TRUSTEE');
INSERT INTO role (name) VALUES ('CEO');
INSERT INTO role (name) VALUES ('AO');