name: CICD

on:
  push:
    branches: [dev]
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Code checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Project
        run : mvn clean install
      - name: Login to Dockerhub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build Docker Image
        run: docker build -t ekalavya/ekalavya .
      - name: Publish image to Dccker hub
        run: docker push ekalavya/ekalavya:latest

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull image from Dockerhub
        run: docker pull ekalavya/ekalavya:latest
      - name: Delete old container
        run: docker rm -f ekalavya/ekalavya
      - name: Run Docker Container
        run: docker run -d -p 8080:8080 --name ekalavya-backend-service ekalavya/ekalavya

